language: php
php:
    - 8.3
    - nightly
matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
cache:
    directories:
        - $HOME/.composer/cache/files
before_script:
    - phpenv global "$TRAVIS_PHP_VERSION"
    - composer config extra.platform.php $TRAVIS_PHP_VERSION
    - composer require php-coveralls/php-coveralls
install:
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    - composer install $flags
script:
    - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
after_script:
    - php vendor/bin/coveralls -v
