language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
matrix:
  allow_failures:
    - php: 5.6
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - echo $TRAVIS_PHP_VERSION
  - phpenv global "$TRAVIS_PHP_VERSION"
  - composer config extra.platform.php $TRAVIS_PHP_VERSION
  - composer require php-coveralls/php-coveralls
  - composer install
script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
