language: php
php:
  - '7.0'
  - '7.1'
cache:
  directories:
    - $HOME/.composer/cache/files
before_script:
  - composer require php-coveralls/php-coveralls
  - composer install
script:
  - ./vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
